site_name: fossdocs
repo_url: https://github.com/cmuc24/fossdocs
theme:
  name: material
  features:
    - navigation.tabs 
    - navigation.indexes
    - content.action.edit
    - content.action.view
    - content.code.copy
